## curl -O https://raw.githubusercontent.com/ravelaso/dj-meneo/main/docker-compose.yml
version: "3.8"
services:
  dj-meneo:
    image: ghcr.io/ravelaso/dj-meneo-prod:latest
    container_name: dj-meneo
    working_dir: /app
    volumes:
      - ./cookies.json:/app/cookies.json  # Mount local file into container
    ports:
      - "3000:3000"
    restart: unless-stopped
